import { ReactNode, useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import axios from "axios";
import styles from "@/styles/Home.module.scss";

interface Cart {
  Itens: ReactNode;
  ID: number;
  Valor_Total: number;
  Usuario_id: number;
  DataCriacao: string;
  DataAlteracao: string;
  Status: string;
}

interface User {
  ID: number;
  name: string;
  email: string;
  username: string;
  password: string;
}

export default function Home() {
  const [carts, setCarts] = useState<Cart[]>([]);
  const [users, setUsers] = useState<User[]>([]);

  useEffect(() => {
    fetchCarts();
    fetchUsers();
  }, []);

  const fetchCarts = async () => {
    try {
      const response = await axios.get<Cart[]>("http://localhost:3001/cart");
      setCarts(response.data);
    } catch (error) {
      console.log(error);
    }
  };

  const fetchUsers = async () => {
    try {
      const response = await axios.get<User[]>("http://localhost:3001/users");
      setUsers(response.data);
    } catch (error) {
      console.log(error);
    }
  };

  const getUserName = (userId: number) => {
    const user = users.find((user) => user.ID === userId);
    return user ? user.name : "";
  };

  return (
    <>
      <Head>
        <title>My Shopping List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <div className={styles.title}>
          <h1>My Shopping List</h1>
        </div>

        <div className={styles.buttons}>
          <table>
            <thead>
              <tr>
                <th>ID</th>
                <th>Criado por</th>
                <th>Itens</th>
              </tr>
            </thead>
            <tbody>
              {carts.map((cart) => (
                <tr key={cart.ID}>
                  <td>{cart.ID}</td>
                  <td>{getUserName(cart.Usuario_id)}</td>
                  <td>{cart.Itens}</td>
                </tr>
              ))}
            </tbody>
          </table>
          <Link legacyBehavior href="/NovaLista" passHref>
            <a>
              <button className={styles.newListButton}>Nova Lista</button>
            </a>
          </Link>
        </div>
      </main>
    </>
  );
}
